[tool.ruff.lint]
select = ["E", "F", "ANN"]

[tool.pyright]
include = ["src"]
venvPath = ".venv"
typeCheckingMode = "standard"
reportUnknownArgumentType = "error"
reportUnknownLambdaType = "error"
reportReturnType = "error"
reportMissingImports = "warning"
pythonVersion = "3.12"
